server:
  port: 8081

spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: guest
    password: guest

logging:
  config:
    classpath: "logback-spring.xml"
  file: url-tracker-api.log